name: hndgroup-logistech

services:
  app:
    image: yovanggaanandhika/laravelpine:8.3
    hostname: hndgroup-logistech-app
    pull_policy: always
    environment:
      APP_NAME: 'HND Group System Logistik'
      APP_ENV: production
      APP_KEY: base64:EBcmQecvKL4nhi0kmw+jy4boUndO9aPTEIJ7DfZ40nA=
      APP_DEBUG: false
      APP_TIMEZONE: Asia/Makassar
      # ----------------------------------------------------------
      APP_URL: https://logistik.hndgroup.id
      FRONTEND_URL: https://logistik.hndgroup.id
      ASSET_URL: https://logistik.hndgroup.id
      # ----------------------------------------------------------
      DKA_DEV_DISABLED_NPM_SERVE: true
      # ----------------------------------------------------------
      APP_LOCALE: id_ID
      APP_FALLBACK_LOCALE: id_ID
      APP_FAKER_LOCALE: id_ID
      APP_MAINTENANCE_DRIVER: file
      # APP_MAINTENANCE_STORE:database
      PHP_CLI_SERVER_WORKERS: 4
      BCRYPT_ROUNDS: 12
      LOG_CHANNEL: stack
      LOG_STACK: single
      LOG_DEPRECATIONS_CHANNEL: null
      LOG_LEVEL: error

      DB_CONNECTION: pgsql
      DB_HOST: hndgroup-logistech-postgresql
      DB_PORT: 5432
      DB_DATABASE: hndgroup_logistech
      DB_USERNAME: postgres
      DB_PASSWORD: '@3ids83jed8dj_3u3hf3hjoiaj2dhfsvnrsvljfwojfojefiuhi3hfk3fiu3hfihf3f3ihf3ihuf3'

      SESSION_DRIVER: database
      SESSION_TABLE: sessions_accounts
      SESSION_LIFETIME: 120
      SESSION_ENCRYPT: false
      SESSION_PATH: /
      SESSION_DOMAIN: null

      BROADCAST_CONNECTION: reverb
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: database

      CACHE_STORE: database
      # CACHE_PREFIX:

      MEMCACHED_HOST: 127.0.0.1

      REDIS_CLIENT: phpredis
      REDIS_HOST: 127.0.0.1
      REDIS_PASSWORD: null
      REDIS_PORT: 6379

      MAIL_MAILER: log
      MAIL_SCHEME: null
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: 2525
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_FROM_ADDRESS: "hello@example.com"
      MAIL_FROM_NAME: "${APP_NAME}"

      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION: us-east-1
      AWS_BUCKET:
      AWS_USE_PATH_STYLE_ENDPOINT: false

      # Server Side (Reverb)
      REVERB_APP_ID: 582743
      REVERB_APP_KEY: 7cjuaglts0v6pkjsajsakjsavazjcjx
      REVERB_APP_SECRET: fatogha3s1idhtg1mtf329320990230932v
      REVERB_HOST: 127.0.0.1
      REVERB_PORT: 8080
      REVERB_SCHEME: http

      # Reverb Server Internal (Di belakang Nginx)
      REVERB_SERVER_HOST: 0.0.0.0
      REVERB_SERVER_PORT: 8080

      # Client Side (Vite/Meta Tag)
      VITE_REVERB_APP_KEY: 7cjuaglts0v6pkjsajsakjsavazjcjx
      VITE_REVERB_HOST: "logistik.hndgroup.id"
      VITE_REVERB_PORT: 443
      VITE_REVERB_SCHEME: https

      THEME_NAME: metronic
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      resources:
        limits:
          cpus: "1.0"
          memory: 800M
        reservations:
          cpus: "0.80"
          memory: 400M
    #ports:
      # service aplikasi Socket (revert)
      #- target: 8080
      #  published: 8080
      #  protocol: tcp
      #  host_ip: 0.0.0.0
      # service aplikasi Backend
      #- target: 80
      #  published: 80
      #  protocol: tcp
      #  host_ip: 0.0.0.0
    volumes:
      - type: volume
        source: storage-data
        target: /var/www/storage/app
    networks:
      - default
      - db

  postgresql:
    image: yovanggaanandhika/postgresql:latest
    container_name: hndgroup-logistech-postgresql
    hostname: hndgroup-logistech-postgresql
    pull_policy: always
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 2
    environment:
      DKA_ROOT_PASSWORD: '@3ids83jed8dj_3u3hf3hjoiaj2dhfsvnrsvljfwojfojefiuhi3hfk3fiu3hfihf3f3ihf3ihuf3'
      DKA_DB_NAME: hndgroup_logistech
      DKA_CRON_ENABLE: false
    deploy:
      resources:
        limits:
          memory: 800M
          #cpus: '0.8'
        reservations:
          memory: 200M
          #cpus: '0.3'
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql
    networks:
      - db

  nginx:
    image: jc21/nginx-proxy-manager
    container_name: hndgroup-logistech-nginx
    hostname: hndgroup-logistech-nginx
    logging:
      driver: local
      options:
        max-size: 10m
        max-file: 10
    ports:
      - target: 80
        published: 80
        protocol: tcp
        host_ip: 0.0.0.0
      - target: 443
        published: 443
        protocol: tcp
        host_ip: 0.0.0.0
      - target: 81
        published: 8181
        protocol: tcp
        host_ip: 0.0.0.0
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 100M
    restart: always
    networks:
      - default
    volumes:
      - type: volume
        source: nginx-data
        target: /data
      - type: volume
        source: nginx-ssl
        target: /etc/letsencrypt

volumes:
  storage-data:
    name: hndgroup-logistech-storage-data
    external: true
  postgres-data:
    name: hndgroup-logistech-postgres-data
    external: true
  nginx-data:
    name: hndgroup-logistech-nginx-data
    external: true
  nginx-ssl:
    name: hndgroup-logistech-postgres-ssl
    external: true

networks:
  default:
    name: hndgroup-logistech
    external: true
  db:
    name: hndgroup-logistech-db
    external: true
