name: stagging-laravelpine

services:
  app:
    build:
      context: .
      dockerfile: stagging.Dockerfile
    container_name: stagging-laravelpine-app
    hostname: stagging-laravelpine-app
    restart: always
    pull_policy: always
    depends_on:
      - mariadb
    environment:
      APP_NAME: DKA
      APP_ENV: production
      APP_KEY: base64:mMKJ+s5Xo3Ylzmf5NLzK+M0WOQx4Hgrt+T5brCRZIMQ=
      APP_DEBUG: true
      APP_URL: http://localhost:8000
      APP_TIMEZONE: Asia/Makassar

      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      APP_FAKER_LOCALE: en_US
      APP_MAINTENANCE_DRIVER: file
      # APP_MAINTENANCE_STORE:database
      PHP_CLI_SERVER_WORKERS: 4
      BCRYPT_ROUNDS: 12
      LOG_CHANNEL: stack
      LOG_STACK: single
      LOG_DEPRECATIONS_CHANNEL: null
      LOG_LEVEL: debug

      DB_CONNECTION: mariadb
      DB_HOST: stagging-laravelpine-mariadb
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel

      SESSION_DRIVER: database
      SESSION_LIFETIME: 120
      SESSION_ENCRYPT: false
      SESSION_PATH: /
      SESSION_DOMAIN: null

      BROADCAST_CONNECTION: log
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: database

      CACHE_STORE: database
      # CACHE_PREFIX:

      MEMCACHED_HOST: 127.0.0.1

      REDIS_CLIENT: phpredis
      REDIS_HOST: 127.0.0.1
      REDIS_PASSWORD: null
      REDIS_PORT: 6379

      MAIL_MAILER: log
      MAIL_SCHEME: null
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: 2525
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_FROM_ADDRESS: "hello@example.com"
      MAIL_FROM_NAME: "${APP_NAME}"

      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION: us-east-1
      AWS_BUCKET:
      AWS_USE_PATH_STYLE_ENDPOINT: false

      VITE_APP_NAME: "${APP_NAME}"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2048M
        reservations:
          cpus: "0.80"
          memory: 1128M
    ports:
      - target: 80
        published: 8000
        protocol: tcp
        host_ip: 0.0.0.0
    networks:
      - default

  mariadb:
    image: yovanggaanandhika/mariadb:latest
    container_name: stagging-laravelpine-mariadb
    hostname: stagging-laravelpine-mariadb
    restart: always
    pull_policy: always
    environment:
      DKA_ROOT_PASSWORD: 'DHJAK12kndk2383dikhjfk34hjk4lk'
      DKA_DB_NAME: laravel
      DKA_DB_USERNAME: laravel
      DKA_DB_PASSWORD: laravel
      # enable cron backup
      DKA_CRON_ENABLE: false
      # run everyday 3:00 AM
      DKA_CRON_PRIODIC: '0 3 * * *'
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: '1.0'
        reservations:
          memory: 200M
          cpus: '0.8'
    ports:
      - target: 3306
        published: 3307
        protocol: tcp
        host_ip: 0.0.0.0
    volumes:
      - type: volume
        source: mariadb-data
        target: /var/lib/mysql
      - type: bind
        source: ./database/backups
        target: /backup
    networks:
      - default

volumes:
  mariadb-data:
    name: stagging-laravelpine-mariadb-data
    driver: local

networks:
  default:
    name: stagging-laravelpine
    driver: bridge
