<?php

namespace App\Services\Resources\Deliveries\Rates;

use App\Repositories\Apps\Deliveries\Rates\DataRatesRepository;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;
use Throwable;

class ResourcesDeliveriesDataRatesServices
{
    protected DataRatesRepository $repository;

    public function __construct()
    {
        $this->repository = new DataRatesRepository();
    }

    /**
     * Store Data Rate
     * @param Request $request
     * @return array
     */
    public function Store(Request $request): array
    {
        DB::beginTransaction();
        try {
            // Validation is assumed to be done in Controller or FormRequest.
            $data = $request->only(['name', 'price', 'category', 'description']);

            // If UUID is not auto-generated by model (it uses HasUuids so it should be),
            // but just in case we need to pass it or other default values.
            // checking model: HasUuids trait handles it.

            $rate = $this->repository->Create($data);

            DB::commit();

            return [
                'status' => true,
                'code' => Response::HTTP_CREATED,
                'msg' => 'Data Rate created successfully',
                'data' => $rate
            ];

        } catch (Throwable $e) {
            DB::rollBack();
            return [
                'status' => false,
                'code' => Response::HTTP_INTERNAL_SERVER_ERROR,
                'msg' => $e->getMessage(),
            ];
        }
    }

    /**
     * Update Data Rate
     * @param Request $request
     * @param string $id
     * @return array
     */
    public function Update(Request $request, string $id): array
    {
        DB::beginTransaction();
        try {
            $rate = $this->repository->Find($id);

            $data = $request->only(['name', 'price', 'category', 'description']);

            $rate->update($data);

            DB::commit();

            return [
                'status' => true,
                'code' => Response::HTTP_OK,
                'msg' => 'Data Rate updated successfully',
                'data' => $rate
            ];

        } catch (ModelNotFoundException $e) {
            DB::rollBack();
            return [
                'status' => false,
                'code' => Response::HTTP_NOT_FOUND,
                'msg' => 'Data Rate not found',
            ];
        } catch (Throwable $e) {
            DB::rollBack();
            return [
                'status' => false,
                'code' => Response::HTTP_INTERNAL_SERVER_ERROR,
                'msg' => $e->getMessage(),
            ];
        }
    }

    /**
     * Delete Data Rate
     * @param string $id
     * @return array
     */
    public function Delete(string $id): array
    {
        DB::beginTransaction();
        try {
            $this->repository->Delete($id);

            DB::commit();

            return [
                'status' => true,
                'code' => Response::HTTP_OK,
                'msg' => 'Data Rate deleted successfully',
            ];

        } catch (ModelNotFoundException $e) {
            DB::rollBack();
            return [
                'status' => false,
                'code' => Response::HTTP_NOT_FOUND,
                'msg' => 'Data Rate not found',
            ];
        } catch (Throwable $e) {
            DB::rollBack();
            return [
                'status' => false,
                'code' => Response::HTTP_INTERNAL_SERVER_ERROR,
                'msg' => $e->getMessage(),
            ];
        }
    }

    public function query(): Builder
    {
        return $this->repository->query();
    }
}
