apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logistik-postgres-pvc
  namespace: hgs-logistik
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logistik-storage-pvc
  namespace: hgs-logistik
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi