<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Delivery Manifest</title>
    <style>
        @page {
            margin: 0cm 0cm;
        }
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 10px;
            margin-top: 3cm;
            margin-bottom: 2cm;
            margin-left: 1cm;
            margin-right: 1cm;
        }
        header {
            position: fixed;
            top: 0cm;
            left: 0cm;
            right: 0cm;
            height: 3cm;
            background-color: #BA0000; /* Dark Red */
            color: white;
            padding: 0 1cm;
            line-height: 1.5cm;
        }
        footer {
            position: fixed;
            bottom: 0cm;
            left: 0cm;
            right: 0cm;
            height: 2cm;
            background-color: #f3f3f3;
            color: #333;
            text-align: center;
            line-height: 1.5cm;
            font-size: 9px;
            border-top: 1px solid #ddd;
        }
        .logo {
            float: left;
            font-size: 24px;
            font-weight: bold;
            padding-top: 0.5cm;
            color: #ffffff;
            text-transform: uppercase;
        }
        .company-info {
            float: right;
            text-align: right;
            font-size: 10px;
            line-height: 1.2;
            padding-top: 0.8cm;
            color: #ccc;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #444;
            padding: 6px;
            text-align: left;
        }
        th {
            background-color: #e0e0e0;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 9px;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .meta-info {
            margin-bottom: 20px;
            border-bottom: 2px solid #1a1a2e;
            padding-bottom: 10px;
        }
        .meta-info h1 {
            margin: 0;
            font-size: 18px;
            color: #1a1a2e;
            text-transform: uppercase;
        }
        .meta-info p {
            margin: 5px 0 0;
            color: #666;
        }
        .signature-section {
            margin-top: 50px;
            page-break-inside: avoid;
        }
        .signature-box {
            float: right;
            width: 200px;
            text-align: center;
        }
        .signature-line {
            border-bottom: 1px solid #000;
            margin-bottom: 5px;
            height: 50px;
        }
    </style>
</head>
<body>
    <header>
        <div class="logo">LOGISTECH</div>
        <div class="company-info">
            HND Logistech Solutions Inc.<br>
            Jalan Andi Mappaodang<br>
            Contact: -
        </div>
    </header>

    <footer>
        Page <span class="pagenum"></span> - Generated by HND Logistech System on {{ now()->format('d M Y H:i:s') }}
    </footer>

    <div class="meta-info">
        <h1>Delivery Manifest Report</h1>
        <p>
            <strong>Period:</strong>
            {{ $startDate ? \Carbon\Carbon::parse($startDate)->format('d M Y') : 'Start' }} -
            {{ $endDate ? \Carbon\Carbon::parse($endDate)->format('d M Y') : 'Now' }}
            | <strong>Total Records:</strong> {{ $reports->count() }}
        </p>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 80px;">Task ID</th>
                <th>Task Name</th>
                <th>Status</th>
                <th>Destination / Recipient</th>
                <th>Assigned Driver(s)</th>
                <th>Volume / Qty</th>
                <th style="width: 80px;">Date Created</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reports as $report)
                <tr>
                    <td><strong>{{ substr($report->id, 0, 8) }}</strong></td>
                    <td>{{ $report->name ?? 'N/A' }}</td>
                    <td>
                        <span style="font-weight:bold; color: {{ ($report->history->sortByDesc('created_at')->first()->to_status ?? '') == 'completed' ? 'green' : 'black' }}">
                            {{ strtoupper($report->history->sortByDesc('created_at')->first()->to_status ?? 'PENDING') }}
                        </span>
                    </td>
                    <td>
                        <strong>{{ $report->destination_model->receipt_name ?? 'N/A' }}</strong><br>
                        <span style="font-size: 8px; color: #555;">{{ Str::limit($report->destination_model->receipt_address ?? 'No Address', 30) }}</span>
                    </td>
                    <td>
                        @php
                            $drivers = collect();
                            foreach($report->assigns as $assign) {
                                if($assign->assignedAccount) {
                                    $drivers->push($assign->assignedAccount);
                                }
                            }
                            $drivers = $drivers->unique('id');
                        @endphp

                        @forelse($drivers as $user)
                            @php
                                // Use getRelation to avoid collision with column name 'information'
                                $info = $user->relationLoaded('information') ? $user->getRelation('information') : null;
                                // If relation not loaded or null, fallback might be needed, but withDefault should handle it if loaded. 
                                // However, since we eager loaded it, getRelation should return the model (or default model).
                                
                                $firstName = $info->first_name ?? '';
                                $lastName = $info->last_name ?? '';
                                $fullName = trim($firstName . ' ' . $lastName);
                                
                                if (empty($fullName)) {
                                    $cred = $user->relationLoaded('credential') ? $user->getRelation('credential') : null;
                                    $fullName = $cred?->username ?? $user->name ?? 'Driver';
                                }
                            @endphp
                            <div>- {{ $fullName }}</div>
                        @empty
                            <span style="color:red; font-style:italic;">Unassigned</span>
                        @endforelse
                    </td>
                    <td>
                        @php
                            $packages = $report->destination_model->packages ?? collect();
                            $pkgCount = $packages->count();
                            $totalWeight = $packages->sum('dimension_weight');
                        @endphp
                        <div><strong>{{ $pkgCount }} Paket</strong></div>
                        <div style="font-size:10px; color:#666;">Wt: {{ $totalWeight }} kg</div>
                    </td>
                    <td>{{ $report->created_at->format('d/m/Y H:i') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="signature-section">
        <div class="signature-box">
            <div class="signature-line"></div>
            <strong>Authorized Signature</strong>
        </div>
    </div>
</body>
</html>
